//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.0
//     from Assets/Scripts/Player/CompanionControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @CompanionControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @CompanionControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CompanionControls"",
    ""maps"": [
        {
            ""name"": ""CompanionCharacterControls"",
            ""id"": ""f12c3bf9-a6b9-40a9-8f8b-070c5391a643"",
            ""actions"": [
                {
                    ""name"": ""MoveCompanion"",
                    ""type"": ""Value"",
                    ""id"": ""37ec1a41-a6f6-4b9e-8000-d15377ebb0b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MakeCompanionJump"",
                    ""type"": ""Button"",
                    ""id"": ""a0170729-9919-40bb-91ab-bc7e3a34977b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""80ac5fb4-d8c3-42cd-b1a5-1713a88a3477"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""795bc7a3-49cb-4f00-839b-e74d8ac45606"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4a9aad4-420f-4447-a7d8-15c2956281c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57393ac2-9a42-467f-978f-d75ff24e1e43"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f4c6e433-3849-42ef-903c-3ebd2ff375c8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ae410a30-22e0-498f-bab5-5e0967ebaf0b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8548cd7f-6325-45d3-8cf6-f65905f6799e"",
                    ""path"": ""<XRController>/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a67208a-fe90-4b82-881b-eb7e868bec4a"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49ce8c2d-228e-407d-ae9c-90643e63b1fe"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53de62f4-b1b2-4451-b7b6-c562a7bdb619"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CompanionCharacterControls
        m_CompanionCharacterControls = asset.FindActionMap("CompanionCharacterControls", throwIfNotFound: true);
        m_CompanionCharacterControls_MoveCompanion = m_CompanionCharacterControls.FindAction("MoveCompanion", throwIfNotFound: true);
        m_CompanionCharacterControls_MakeCompanionJump = m_CompanionCharacterControls.FindAction("MakeCompanionJump", throwIfNotFound: true);
    }

    ~@CompanionControls()
    {
        UnityEngine.Debug.Assert(!m_CompanionCharacterControls.enabled, "This will cause a leak and performance issues, CompanionControls.CompanionCharacterControls.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CompanionCharacterControls
    private readonly InputActionMap m_CompanionCharacterControls;
    private List<ICompanionCharacterControlsActions> m_CompanionCharacterControlsActionsCallbackInterfaces = new List<ICompanionCharacterControlsActions>();
    private readonly InputAction m_CompanionCharacterControls_MoveCompanion;
    private readonly InputAction m_CompanionCharacterControls_MakeCompanionJump;
    public struct CompanionCharacterControlsActions
    {
        private @CompanionControls m_Wrapper;
        public CompanionCharacterControlsActions(@CompanionControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveCompanion => m_Wrapper.m_CompanionCharacterControls_MoveCompanion;
        public InputAction @MakeCompanionJump => m_Wrapper.m_CompanionCharacterControls_MakeCompanionJump;
        public InputActionMap Get() { return m_Wrapper.m_CompanionCharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CompanionCharacterControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICompanionCharacterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Add(instance);
            @MoveCompanion.started += instance.OnMoveCompanion;
            @MoveCompanion.performed += instance.OnMoveCompanion;
            @MoveCompanion.canceled += instance.OnMoveCompanion;
            @MakeCompanionJump.started += instance.OnMakeCompanionJump;
            @MakeCompanionJump.performed += instance.OnMakeCompanionJump;
            @MakeCompanionJump.canceled += instance.OnMakeCompanionJump;
        }

        private void UnregisterCallbacks(ICompanionCharacterControlsActions instance)
        {
            @MoveCompanion.started -= instance.OnMoveCompanion;
            @MoveCompanion.performed -= instance.OnMoveCompanion;
            @MoveCompanion.canceled -= instance.OnMoveCompanion;
            @MakeCompanionJump.started -= instance.OnMakeCompanionJump;
            @MakeCompanionJump.performed -= instance.OnMakeCompanionJump;
            @MakeCompanionJump.canceled -= instance.OnMakeCompanionJump;
        }

        public void RemoveCallbacks(ICompanionCharacterControlsActions instance)
        {
            if (m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICompanionCharacterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CompanionCharacterControlsActions @CompanionCharacterControls => new CompanionCharacterControlsActions(this);
    public interface ICompanionCharacterControlsActions
    {
        void OnMoveCompanion(InputAction.CallbackContext context);
        void OnMakeCompanionJump(InputAction.CallbackContext context);
    }
}
