//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.0
//     from Assets/Scripts/Player/CompanionControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Scripts/Player/CompanionControls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @CompanionControls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @CompanionControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""CompanionControls"",
    ""maps"": [
        {
            ""name"": ""CompanionCharacterControls"",
            ""id"": ""f12c3bf9-a6b9-40a9-8f8b-070c5391a643"",
            ""actions"": [
                {
                    ""name"": ""MoveCompanion"",
                    ""type"": ""Value"",
                    ""id"": ""37ec1a41-a6f6-4b9e-8000-d15377ebb0b2"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""NormalizeVector2"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MakeCompanionJump"",
                    ""type"": ""Button"",
                    ""id"": ""a0170729-9919-40bb-91ab-bc7e3a34977b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""80ac5fb4-d8c3-42cd-b1a5-1713a88a3477"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": ""StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""795bc7a3-49cb-4f00-839b-e74d8ac45606"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""e4a9aad4-420f-4447-a7d8-15c2956281c4"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""57393ac2-9a42-467f-978f-d75ff24e1e43"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""f4c6e433-3849-42ef-903c-3ebd2ff375c8"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""ae410a30-22e0-498f-bab5-5e0967ebaf0b"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""8548cd7f-6325-45d3-8cf6-f65905f6799e"",
                    ""path"": ""<XRController>{LeftHand}/joystick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveCompanion"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8a67208a-fe90-4b82-881b-eb7e868bec4a"",
                    ""path"": ""<XRController>{LeftHand}/{TriggerButton}"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""49ce8c2d-228e-407d-ae9c-90643e63b1fe"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""53de62f4-b1b2-4451-b7b6-c562a7bdb619"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MakeCompanionJump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CompanionCharacterControls
        m_CompanionCharacterControls = asset.FindActionMap("CompanionCharacterControls", throwIfNotFound: true);
        m_CompanionCharacterControls_MoveCompanion = m_CompanionCharacterControls.FindAction("MoveCompanion", throwIfNotFound: true);
        m_CompanionCharacterControls_MakeCompanionJump = m_CompanionCharacterControls.FindAction("MakeCompanionJump", throwIfNotFound: true);
    }

    ~@CompanionControls()
    {
        UnityEngine.Debug.Assert(!m_CompanionCharacterControls.enabled, "This will cause a leak and performance issues, CompanionControls.CompanionCharacterControls.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CompanionCharacterControls
    private readonly InputActionMap m_CompanionCharacterControls;
    private List<ICompanionCharacterControlsActions> m_CompanionCharacterControlsActionsCallbackInterfaces = new List<ICompanionCharacterControlsActions>();
    private readonly InputAction m_CompanionCharacterControls_MoveCompanion;
    private readonly InputAction m_CompanionCharacterControls_MakeCompanionJump;
    /// <summary>
    /// Provides access to input actions defined in input action map "CompanionCharacterControls".
    /// </summary>
    public struct CompanionCharacterControlsActions
    {
        private @CompanionControls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public CompanionCharacterControlsActions(@CompanionControls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "CompanionCharacterControls/MoveCompanion".
        /// </summary>
        public InputAction @MoveCompanion => m_Wrapper.m_CompanionCharacterControls_MoveCompanion;
        /// <summary>
        /// Provides access to the underlying input action "CompanionCharacterControls/MakeCompanionJump".
        /// </summary>
        public InputAction @MakeCompanionJump => m_Wrapper.m_CompanionCharacterControls_MakeCompanionJump;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_CompanionCharacterControls; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="CompanionCharacterControlsActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(CompanionCharacterControlsActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="CompanionCharacterControlsActions" />
        public void AddCallbacks(ICompanionCharacterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Add(instance);
            @MoveCompanion.started += instance.OnMoveCompanion;
            @MoveCompanion.performed += instance.OnMoveCompanion;
            @MoveCompanion.canceled += instance.OnMoveCompanion;
            @MakeCompanionJump.started += instance.OnMakeCompanionJump;
            @MakeCompanionJump.performed += instance.OnMakeCompanionJump;
            @MakeCompanionJump.canceled += instance.OnMakeCompanionJump;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="CompanionCharacterControlsActions" />
        private void UnregisterCallbacks(ICompanionCharacterControlsActions instance)
        {
            @MoveCompanion.started -= instance.OnMoveCompanion;
            @MoveCompanion.performed -= instance.OnMoveCompanion;
            @MoveCompanion.canceled -= instance.OnMoveCompanion;
            @MakeCompanionJump.started -= instance.OnMakeCompanionJump;
            @MakeCompanionJump.performed -= instance.OnMakeCompanionJump;
            @MakeCompanionJump.canceled -= instance.OnMakeCompanionJump;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="CompanionCharacterControlsActions.UnregisterCallbacks(ICompanionCharacterControlsActions)" />.
        /// </summary>
        /// <seealso cref="CompanionCharacterControlsActions.UnregisterCallbacks(ICompanionCharacterControlsActions)" />
        public void RemoveCallbacks(ICompanionCharacterControlsActions instance)
        {
            if (m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="CompanionCharacterControlsActions.AddCallbacks(ICompanionCharacterControlsActions)" />
        /// <seealso cref="CompanionCharacterControlsActions.RemoveCallbacks(ICompanionCharacterControlsActions)" />
        /// <seealso cref="CompanionCharacterControlsActions.UnregisterCallbacks(ICompanionCharacterControlsActions)" />
        public void SetCallbacks(ICompanionCharacterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CompanionCharacterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="CompanionCharacterControlsActions" /> instance referencing this action map.
    /// </summary>
    public CompanionCharacterControlsActions @CompanionCharacterControls => new CompanionCharacterControlsActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "CompanionCharacterControls" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="CompanionCharacterControlsActions.AddCallbacks(ICompanionCharacterControlsActions)" />
    /// <seealso cref="CompanionCharacterControlsActions.RemoveCallbacks(ICompanionCharacterControlsActions)" />
    public interface ICompanionCharacterControlsActions
    {
        /// <summary>
        /// Method invoked when associated input action "MoveCompanion" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMoveCompanion(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "MakeCompanionJump" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMakeCompanionJump(InputAction.CallbackContext context);
    }
}
